// ─── POM GENERATOR ───────────────────────────────────────────────────────────

function toClassName(pageTitle) {
  return (pageTitle || 'MyPage')
    .replace(/[^a-zA-Z0-9\s]/g, '').trim()
    .split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('') + 'Page';
}

// Builds a unique-per-element property-name resolver. Two elements sharing
// the same visible label (e.g. two "Submit" buttons) would otherwise produce
// duplicate identifiers — silently overwritten in JS, a compile error in Java.
function makePropResolver() {
  const seen = new Map(); // base name -> count used so far
  return (label) => {
    const base = (label || 'element').replace(/[^a-zA-Z0-9\s]/g, '').trim()
      .split(/\s+/).map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1)).join('') || 'element';
    const count = seen.get(base) || 0;
    seen.set(base, count + 1);
    return count === 0 ? base : `${base}${count + 1}`;
  };
}

function generatePlaywrightPOM(locators, pageTitle, url, locatorTypes) {
  const className = toClassName(pageTitle);
  const nextProp = makePropResolver();

  const wantXPath      = locatorTypes.includes('xpath');
  const wantCSS        = locatorTypes.includes('css');
  const wantPlaywright = locatorTypes.includes('playwright');

  const propNames = new Map(); // locator -> resolved prop name, reused below
  const resolveProp = (l) => {
    if (!propNames.has(l)) propNames.set(l, nextProp(l.elementLabel));
    return propNames.get(l);
  };

  const props = locators.map(l => {
    const prop = resolveProp(l);
    const lines = [`\n  // ${l.elementType} | ${l.locatorStrategy} | Confidence: ${l.confidence}`];
    if (wantPlaywright && l.playwrightLocator)
      lines.push(`  get ${prop}() { return this.page.${l.playwrightLocator}; }`);
    if (wantCSS && l.cssSelector)
      lines.push(`  get ${prop}ByCss() { return this.page.locator('${l.cssSelector.replace(/'/g,"\\'")}'); }`);
    if (wantXPath && l.xpath)
      lines.push(`  get ${prop}ByXPath() { return this.page.locator('xpath=${l.xpath.replace(/'/g,"\\'")}'); }`);
    return lines.join('\n');
  }).join('\n');

  // Use best available locator for action methods
  const bestLocator = (l) => {
    const prop = resolveProp(l);
    if (wantPlaywright && l.playwrightLocator) return `this.page.${l.playwrightLocator}`;
    if (wantCSS && l.cssSelector)             return `this.page.locator('${l.cssSelector.replace(/'/g,"\\'")}')`;
    if (wantXPath && l.xpath)                 return `this.page.locator('xpath=${l.xpath.replace(/'/g,"\\'")}')`;
    return `this.${prop}`;
  };

  const actions = locators
    .filter(l => ['input','button','a','select','textarea'].includes(l.elementType))
    .slice(0, 8).map(l => {
      const prop = resolveProp(l);
      const P = prop.charAt(0).toUpperCase() + prop.slice(1);
      const loc = bestLocator(l);
      if (l.elementType === 'input' || l.elementType === 'textarea')
        return `\n  async fill${P}(value) { await ${loc}.fill(value); }`;
      if (l.elementType === 'button' || l.elementType === 'a')
        return `\n  async click${P}() { await ${loc}.click(); }`;
      if (l.elementType === 'select')
        return `\n  async select${P}(value) { await ${loc}.selectOption(value); }`;
      return '';
    }).join('');

  const selectedTypes = locatorTypes.map(t =>
    t === 'playwright' ? 'Playwright built-in' : t.toUpperCase()
  ).join(', ');

  return `// ============================================================
// Page Object Model — Auto-generated by AI LocatorX
// Page     : ${pageTitle}
// URL      : ${url}
// Date     : ${new Date().toISOString().split('T')[0]}
// Locators : ${selectedTypes}
// Note     : Only HIGH confidence, visible & verified locators
// ============================================================

const { expect } = require('@playwright/test');

class ${className} {
  /** @param {import('@playwright/test').Page} page */
  constructor(page) {
    this.page = page;
    this.url  = '${url}';
  }

  async navigate() { await this.page.goto(this.url); }

  // ── Locators ──────────────────────────────────────────────
${props}

  // ── Actions ───────────────────────────────────────────────
${actions}

  // ── Helpers ───────────────────────────────────────────────
  async waitForPageLoad() { await this.page.waitForLoadState('networkidle'); }
}

module.exports = { ${className} };
`;
}

// Java + Selenium WebDriver, PageFactory @FindBy style. CSS is preferred over
// XPath when both are available (faster, more idiomatic in Selenium); falls
// back to XPath only when no CSS selector exists for that element. Playwright
// built-in locators (getByRole, etc.) have no Selenium equivalent, so elements
// that only have a playwrightLocator and no xpath/css are skipped.
function generateJavaPOM(locators, pageTitle, url) {
  const className = toClassName(pageTitle);
  const nextProp = makePropResolver();
  const propNames = new Map();
  const resolveProp = (l) => {
    if (!propNames.has(l)) propNames.set(l, nextProp(l.elementLabel));
    return propNames.get(l);
  };

  // @FindBy strategy for a given locator — CSS first, XPath fallback.
  const findByOf = (l) => {
    if (l.cssSelector) return { kind: 'css', value: l.cssSelector };
    if (l.xpath)       return { kind: 'xpath', value: l.xpath };
    return null;
  };

  const fields = [];
  const usable = []; // { locator, prop, findBy }
  for (const l of locators) {
    const findBy = findByOf(l);
    if (!findBy) continue; // no CSS/XPath available for this element — skip in Java POM
    const prop = resolveProp(l);
    usable.push({ locator: l, prop, findBy });
    const escaped = findBy.value.replace(/"/g, '\\"');
    fields.push(
      `\n    // ${l.elementType} | ${l.locatorStrategy} | Confidence: ${l.confidence}` +
      `\n    @FindBy(${findBy.kind} = "${escaped}")` +
      `\n    private WebElement ${prop};`
    );
  }

  const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

  const actions = usable
    .filter(u => ['input','button','a','select','textarea'].includes(u.locator.elementType))
    .slice(0, 8).map(u => {
      const P = cap(u.prop);
      const type = u.locator.elementType;
      if (type === 'input' || type === 'textarea')
        return `\n    public void fill${P}(String value) {\n        ${u.prop}.clear();\n        ${u.prop}.sendKeys(value);\n    }`;
      if (type === 'button' || type === 'a')
        return `\n    public void click${P}() {\n        ${u.prop}.click();\n    }`;
      if (type === 'select')
        return `\n    public void select${P}(String visibleText) {\n        new Select(${u.prop}).selectByVisibleText(visibleText);\n    }`;
      return '';
    }).join('\n');

  const skipped = locators.length - usable.length;
  const skippedNote = skipped > 0
    ? `\n// Note     : ${skipped} element(s) skipped — no CSS/XPath available (Playwright-only locator)`
    : '';

  return `// ============================================================
// Page Object Model — Auto-generated by AI LocatorX
// Page     : ${pageTitle}
// URL      : ${url}
// Date     : ${new Date().toISOString().split('T')[0]}
// Locators : Selenium WebDriver (CSS preferred, XPath fallback)${skippedNote}
// Note     : Only HIGH confidence, visible & verified locators
// ============================================================

package com.locators.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;

public class ${className} {

    private final WebDriver driver;
    private final String url = "${url}";
${fields.join('\n')}

    public ${className}(WebDriver driver) {
        this.driver = driver;
        PageFactory.initElements(driver, this);
    }

    public void navigate() {
        driver.get(url);
    }
${actions}
}
`;
}

function generatePOM(locators, pageTitle, url, locatorTypes, format = 'playwright') {
  if (format === 'java') return generateJavaPOM(locators, pageTitle, url);
  return generatePlaywrightPOM(locators, pageTitle, url, locatorTypes);
}

module.exports = { generatePOM };
